apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagingbackend-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messagingbackend-dev
  template:
    metadata:
      labels:
        app: messagingbackend-dev
    spec:
      containers:
        - name: messagingbackend-dev
          image: mezohub.azurecr.io/messagingbackend
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "450Mi"
              cpu: "300m"
          env:
            - name: NODE_ENV
              value: "development"
          ports:
            - containerPort: 3002
          readinessProbe:
            httpGet:
              path: /api
              port: 3002
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /api
              port: 3002
            initialDelaySeconds: 300
            periodSeconds: 60
            successThreshold: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - devpool

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: messagingbackend-autoscaler
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: messagingbackend-dev
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95
