apiVersion: v1
kind: Service
metadata:
    name: messagingbackend
    namespace: production
    labels:
        app.kubernetes.io/name: messagingbackend-svc
spec:
    type: ClusterIP
    ports:
        - port: 3002
          name: http
    selector:
        app: messagingbackend
