apiVersion: v1
kind: Service
metadata:
    name: messagingbackend-dev
    labels:
        app.kubernetes.io/name: messagingbackend-dev-svc
spec:
    type: ClusterIP
    ports:
        - name: http
          port: 3002
    selector:
        app: messagingbackend-dev
